server {
    listen 80;

    # 1. Route for our UI (Serve the React static files)
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # Fixes React Router page refreshes
        try_files $uri $uri/ /index.html; 
    }

    # 2. Route for our APIs (Forward to the hidden backend container)
    location /api/ {
        # 'backend' is the exact name of the service in docker-compose.prod.yml
        proxy_pass http://${BACKEND_HOST}:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 3. Route for our Images (Forward to the hidden MinIO container)
    location /storage/ {
        # Rewrites /storage/bucket/image.jpg -> /bucket/image.jpg for MinIO
        rewrite ^/storage/(.*) /$1 break;
        proxy_pass http://${MINIO_HOST}:9000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}