version: "3.8"

services:
  # The Bouncer: The only container exposed to the internet
  frontend:
    image: shivamthaker369/docker-volume-frontend:latest
    ports:
      - "80:80"
    restart: always
    environment:
      # These must match your service names in docker-compose.yml
      - BACKEND_HOST=backend
      - MINIO_HOST=minio
    depends_on:
      - backend

  backend:
    image: shivamthaker369/docker-volume-backend:latest
    # NO PORTS EXPOSED. Protected inside the Docker network.
    restart: always
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - STORAGE_TYPE=s3
      - S3_ENDPOINT=http://minio:9000
      - S3_ACCESS_KEY=${PROD_S3_KEY}
      - S3_SECRET_KEY=${PROD_S3_SECRET}
      - S3_BUCKET=uploads
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    # NO PORTS EXPOSED. Protected inside the Docker network.
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio
    # NO PORTS EXPOSED. Nginx will route public traffic here securely.
    restart: always
    environment:
      - MINIO_ROOT_USER=${PROD_S3_KEY}
      - MINIO_ROOT_PASSWORD=${PROD_S3_SECRET}
    command: server /data
    volumes:
      - minio_data:/data

volumes:
  pgdata:
  minio_data:
